### PR TITLE
script to automate analytics additions

### PR DESCRIPTION
**Pull request by Div-c3d**
# Description

Tool to automatically scan project for preexisting analytics events and insert corresponding Cognitive3d custom events

Height Task ID (If applicable):

## Type of change

  - [ ] Bug fix (non-breaking change which fixes an issue)
  - [x] New feature (non-breaking change which adds functionality)
  - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - [ ] This change requires a documentation update

# Checklist:

  - [ ] My code follows the style guidelines of this project
  - [ ] I have performed a self-review of my own code
  - [ ] I have commented my code, particularly in hard-to-understand areas
  - [ ] I have made corresponding changes to the documentation
  - [ ] My changes generate no new warnings
  - [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by matt-manuel** [comment]
Hi Div - Looks like you have a few Codacy recommendations / requirements still to update. Let Calder and Atif know when you've updated your code so they can review before merging your branch. Thanks!

**Comment by Div-c3d** [comment]
> Hi Div - Looks like you have a few Codacy recommendations / requirements still to update. Let Calder and Atif know when you've updated your code so they can review before merging your branch. Thanks!

I think they're good to go now? Only warnings remain that seem benign

**Comment by calderarchinuk** [comment]
Can you add the Cognitive3D namespace?

**Comment by Labec** [comment]
> Can you add the Cognitive3D namespace?

@Div-c3d see above

**Comment by matt-manuel** [comment]
@AtifMahmud Any harm in approving and closing this PR? Or should we nuke it. It was Div's hackathon project.

**Comment by AtifMahmud** [comment]
> @AtifMahmud Any harm in approving and closing this PR? Or should we nuke it. It was Div's hackathon project.

@matt-manuel a few more changes need to be made before we can merge.
https://c3d.height.app/T-3700

**Pull request closed without merging**
